---
- name: add an apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg

- name: add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: install
  ansible.builtin.apt:
    name: "helm={{ helm_version }}"
    state: present
    
- name: remove repository from sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    state: absent
