---
- name: Install Containerd
  hosts: staging
  become: true
  become_user: root
  roles:
    - containerd

- name: Install Kubernetes
  hosts: staging
  become: true
  become_user: root
  environment:
   KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - kubeadm

- name: Install Helm & Kubectl
  hosts: staging
  become: true
  become_user: root
  roles:
    - kube_cli

- name: Install Cilium
  hosts: staging
  become: true
  become_user: root
  roles:
    - cilium
