---
- name: Kubeadm init with pre-generated token
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - "--kubernetes-version=v{{ kubeadm_tool_version }}"
      - "--service-cidr={{ kubeadm_service_cidr }}"
      - "--pod-network-cidr={{ kubeadm_pod_network_cidr }}"
      - "--token={{ kubeadm_token }}"
      - "--skip-phases=addon/kube-proxy"
    creates: /var/lib/kubelet/ansible-idempotency
