---
- name: Copy manifests directory to /tmp
  ansible.builtin.copy:
    src: manifests
    dest: /tmp
    mode: '0600'
    force: false

- name: Deploy calico operator
  ansible.builtin.command: kubectl create -f /tmp/manifests/calico/tigera-operator.yml
  args:
    creates: /var/lib/kubelet/ansible-idempotency

- name: Deploy calico custom-resources
  ansible.builtin.command: kubectl create -f /tmp/manifests/calico/custom-resources.yml
  args:
    creates: /var/lib/kubelet/ansible-idempotency

- name: Deploy metrics-server
  ansible.builtin.command: kubectl apply -f /tmp/manifests/metrics-server
  args:
    creates: /var/lib/kubelet/ansible-idempotency

- name: Deploy openebs
  ansible.builtin.command: kubectl apply -f /tmp/manifests/openebs
  args:
    creates: /var/lib/kubelet/ansible-idempotency

- name: Pause for 1 minute in order to get kubernetes ready
  ansible.builtin.pause:
    minutes: 1
