---
- name: Create file in /var/lib/kubelet in order to get idempotency
  ansible.builtin.file:
    path: /var/lib/kubelet/ansible-idempotency
    state: touch
    owner: root
    group: root
    mode: '0600'
