---
- name: Allow permissive RBAC rules
  ansible.builtin.command:
    argv:
      - kubectl
      - create
      - clusterrolebinding
      - permissive-binding
      - --clusterrole=cluster-admin
      - --user=admin
      - --user=kubelet
      - --group=system:serviceaccounts
    creates: /var/lib/kubelet/ansible-idempotency

- name: Taint controller node
  ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  args:
    creates: /var/lib/kubelet/ansible-idempotency
