---
# tasks file for kubeadm
- name: Include tasks of kubeadm-install
  ansible.builtin.include_tasks:
    file: kubeadm-install.yml

- name: Include tasks of kubeadm-init
  ansible.builtin.include_tasks:
    file: kubeadm-init.yml

- name: Include tasks of kubeadm-config
  ansible.builtin.include_tasks:
    file: kubeadm-config.yml

- name: Include tasks of kubeadm-addons
  ansible.builtin.include_tasks:
    file: kubeadm-addons.yml

- name: Include tasks of kubeadm-idempotency
  ansible.builtin.include_tasks:
    file: kubeadm-idempotency.yml
