---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - bash-completion

- name: Add docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add repository into sources list
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    update_cache: true

- name: Install containerd
  ansible.builtin.apt:
    pkg:
    - containerd.io={{ containerd_version }}
  
- name: Remove repository from sources list
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    update_cache: true

- name: Enable containerd
  ansible.builtin.service:
    name: containerd
    enabled: yes
